print("Why Python is just for you in terms of automation/programming/testing/extension?")
print("Why shell scripts can't replace Python scripts?")
print("Why C/C++/Java can't replace Python?")
print("Why is Python better than Shell?")
print("Why is Python better than C?")
print("Why is Python better than Pearl?")
print("What about Python allows you to split your code?")
print("Why will Python save you time?")
print("Why are Python programs shorter and easier to read?")
print("Why is Python extensible?*")
print("What is Python named after?*")
